// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

type AbandonTaskRequest struct {
	// id
	ID int64 `pathParam:"style=simple,explode=false,name=id"`
}

func (o *AbandonTaskRequest) GetID() int64 {
	if o == nil {
		return 0
	}
	return o.ID
}

type AbandonTaskResponse struct {
}
