// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/unclesp1d3r/cipherswarm-agent-sdk/models/components"
)

type AbandonTaskRequest struct {
	// id
	ID int64 `pathParam:"style=simple,explode=false,name=id"`
}

func (o *AbandonTaskRequest) GetID() int64 {
	if o == nil {
		return 0
	}
	return o.ID
}

type AbandonTaskResponse struct {
	HTTPMeta components.HTTPMetadata
}

func (o *AbandonTaskResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}
