// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/unclesp1d3r/cipherswarm-agent-sdk-go/models/components"
)

type AuthenticateResponse struct {
	HTTPMeta components.HTTPMetadata
	// successful
	AuthenticationResult *components.AuthenticationResult
}

func (o *AuthenticateResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *AuthenticateResponse) GetAuthenticationResult() *components.AuthenticationResult {
	if o == nil {
		return nil
	}
	return o.AuthenticationResult
}
