// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/unclesp1d3r/cipherswarm-agent-sdk/models/components"
)

type CheckForCrackerUpdateRequest struct {
	// operating_system
	OperatingSystem *string `queryParam:"style=form,explode=true,name=operating_system"`
	// version
	Version *string `queryParam:"style=form,explode=true,name=version"`
}

func (o *CheckForCrackerUpdateRequest) GetOperatingSystem() *string {
	if o == nil {
		return nil
	}
	return o.OperatingSystem
}

func (o *CheckForCrackerUpdateRequest) GetVersion() *string {
	if o == nil {
		return nil
	}
	return o.Version
}

type CheckForCrackerUpdateResponse struct {
	HTTPMeta components.HTTPMetadata
	// operating system not found
	CrackerUpdate *components.CrackerUpdate
}

func (o *CheckForCrackerUpdateResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CheckForCrackerUpdateResponse) GetCrackerUpdate() *components.CrackerUpdate {
	if o == nil {
		return nil
	}
	return o.CrackerUpdate
}
