// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/unclesp1d3r/cipherswarm-agent-sdk-go/models/components"
)

type ConfigurationResponse struct {
	HTTPMeta components.HTTPMetadata
	// successful
	AgentConfiguration *components.AgentConfiguration
}

func (o *ConfigurationResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *ConfigurationResponse) GetAgentConfiguration() *components.AgentConfiguration {
	if o == nil {
		return nil
	}
	return o.AgentConfiguration
}
