// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

type HashListAttackRequest struct {
	// id
	ID int64 `pathParam:"style=simple,explode=false,name=id"`
}

func (o *HashListAttackRequest) GetID() int64 {
	if o == nil {
		return 0
	}
	return o.ID
}
