// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/unclesp1d3r/cipherswarm-agent-sdk-go/models/components"
)

type NewTaskResponse struct {
	HTTPMeta components.HTTPMetadata
	// new task available
	Task *components.Task
}

func (o *NewTaskResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *NewTaskResponse) GetTask() *components.Task {
	if o == nil {
		return nil
	}
	return o.Task
}
