// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/unclesp1d3r/cipherswarm-agent-sdk-go/models/components"
	"net/http"
)

type SendCrackRequest struct {
	// id
	ID            int64                     `pathParam:"style=simple,explode=false,name=id"`
	HashcatResult *components.HashcatResult `request:"mediaType=application/json"`
}

func (o *SendCrackRequest) GetID() int64 {
	if o == nil {
		return 0
	}
	return o.ID
}

func (o *SendCrackRequest) GetHashcatResult() *components.HashcatResult {
	if o == nil {
		return nil
	}
	return o.HashcatResult
}

type SendCrackResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *SendCrackResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *SendCrackResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *SendCrackResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
