// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/unclesp1d3r/cipherswarm-agent-sdk/models/components"
)

type ShowAttackRequest struct {
	// id
	ID int64 `pathParam:"style=simple,explode=false,name=id"`
}

func (o *ShowAttackRequest) GetID() int64 {
	if o == nil {
		return 0
	}
	return o.ID
}

type ShowAttackResponse struct {
	HTTPMeta components.HTTPMetadata
	// successful
	Attack *components.Attack
}

func (o *ShowAttackResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *ShowAttackResponse) GetAttack() *components.Attack {
	if o == nil {
		return nil
	}
	return o.Attack
}
