// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/unclesp1d3r/cipherswarm-agent-sdk/models/components"
)

type ShowTaskRequest struct {
	// id
	ID int64 `pathParam:"style=simple,explode=false,name=id"`
}

func (o *ShowTaskRequest) GetID() int64 {
	if o == nil {
		return 0
	}
	return o.ID
}

type ShowTaskResponse struct {
	HTTPMeta components.HTTPMetadata
	// successful
	Task *components.Task
}

func (o *ShowTaskResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *ShowTaskResponse) GetTask() *components.Task {
	if o == nil {
		return nil
	}
	return o.Task
}
