// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/unclesp1d3r/cipherswarm-agent-sdk-go/models/components"
	"net/http"
)

type SubmitStatusRequest struct {
	// id
	ID int64 `pathParam:"style=simple,explode=false,name=id"`
	// status
	TaskStatus components.TaskStatus `request:"mediaType=application/json"`
}

func (o *SubmitStatusRequest) GetID() int64 {
	if o == nil {
		return 0
	}
	return o.ID
}

func (o *SubmitStatusRequest) GetTaskStatus() components.TaskStatus {
	if o == nil {
		return components.TaskStatus{}
	}
	return o.TaskStatus
}

type SubmitStatusResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *SubmitStatusResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *SubmitStatusResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *SubmitStatusResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
