// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/unclesp1d3r/cipherswarm-agent-sdk-go/models/components"
	"net/http"
)

type SubmitErrorAgentRequest struct {
	// id
	ID         int64                  `pathParam:"style=simple,explode=false,name=id"`
	AgentError *components.AgentError `request:"mediaType=application/json"`
}

func (o *SubmitErrorAgentRequest) GetID() int64 {
	if o == nil {
		return 0
	}
	return o.ID
}

func (o *SubmitErrorAgentRequest) GetAgentError() *components.AgentError {
	if o == nil {
		return nil
	}
	return o.AgentError
}

type SubmitErrorAgentResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *SubmitErrorAgentResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *SubmitErrorAgentResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *SubmitErrorAgentResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
