// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/unclesp1d3r/cipherswarm-agent-sdk-go/models/components"
)

type SubmitStatusRequest struct {
	// id
	ID int64 `pathParam:"style=simple,explode=false,name=id"`
	// status
	TaskStatus components.TaskStatus `request:"mediaType=application/json"`
}

func (o *SubmitStatusRequest) GetID() int64 {
	if o == nil {
		return 0
	}
	return o.ID
}

func (o *SubmitStatusRequest) GetTaskStatus() components.TaskStatus {
	if o == nil {
		return components.TaskStatus{}
	}
	return o.TaskStatus
}

type SubmitStatusResponse struct {
}
