// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/unclesp1d3r/cipherswarm-agent-sdk/models/components"
)

type UpdateAgentRequest struct {
	// id
	ID          int64                   `pathParam:"style=simple,explode=false,name=id"`
	AgentUpdate *components.AgentUpdate `request:"mediaType=application/json"`
}

func (o *UpdateAgentRequest) GetID() int64 {
	if o == nil {
		return 0
	}
	return o.ID
}

func (o *UpdateAgentRequest) GetAgentUpdate() *components.AgentUpdate {
	if o == nil {
		return nil
	}
	return o.AgentUpdate
}

type UpdateAgentResponse struct {
	HTTPMeta components.HTTPMetadata
	// successful
	Agent *components.Agent
}

func (o *UpdateAgentResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *UpdateAgentResponse) GetAgent() *components.Agent {
	if o == nil {
		return nil
	}
	return o.Agent
}
