// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/unclesp1d3r/cipherswarm-agent-sdk-go/models/components"
	"net/http"
)

type UpdateAgentRequest struct {
	// id
	ID          int64                   `pathParam:"style=simple,explode=false,name=id"`
	AgentUpdate *components.AgentUpdate `request:"mediaType=application/json"`
}

func (o *UpdateAgentRequest) GetID() int64 {
	if o == nil {
		return 0
	}
	return o.ID
}

func (o *UpdateAgentRequest) GetAgentUpdate() *components.AgentUpdate {
	if o == nil {
		return nil
	}
	return o.AgentUpdate
}

type UpdateAgentResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// successful
	Agent *components.Agent
}

func (o *UpdateAgentResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *UpdateAgentResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *UpdateAgentResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *UpdateAgentResponse) GetAgent() *components.Agent {
	if o == nil {
		return nil
	}
	return o.Agent
}
