// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
)

// ErrorObject - Not authorized
type ErrorObject struct {
	Error_ *string `json:"error,omitempty"`
}

var _ error = &ErrorObject{}

func (e *ErrorObject) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
