// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
)

type StateError struct {
	State []string `json:"state,omitempty"`
}

var _ error = &StateError{}

func (e *StateError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
