// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type AdvancedAgentConfiguration struct {
	// The interval in seconds to check for agent updates
	AgentUpdateInterval *int64 `json:"agent_update_interval"`
	// Use the hashcat binary already installed on the client system
	UseNativeHashcat *bool `json:"use_native_hashcat"`
	// The device to use for hashcat
	BackendDevice *string `json:"backend_device"`
}

func (o *AdvancedAgentConfiguration) GetAgentUpdateInterval() *int64 {
	if o == nil {
		return nil
	}
	return o.AgentUpdateInterval
}

func (o *AdvancedAgentConfiguration) GetUseNativeHashcat() *bool {
	if o == nil {
		return nil
	}
	return o.UseNativeHashcat
}

func (o *AdvancedAgentConfiguration) GetBackendDevice() *string {
	if o == nil {
		return nil
	}
	return o.BackendDevice
}
