// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type AdvancedAgentConfiguration struct {
	AgentUpdateInterval *int64  `json:"agent_update_interval"`
	UseNativeHashcat    *bool   `json:"use_native_hashcat"`
	BackendDevice       *string `json:"backend_device"`
}

func (o *AdvancedAgentConfiguration) GetAgentUpdateInterval() *int64 {
	if o == nil {
		return nil
	}
	return o.AgentUpdateInterval
}

func (o *AdvancedAgentConfiguration) GetUseNativeHashcat() *bool {
	if o == nil {
		return nil
	}
	return o.UseNativeHashcat
}

func (o *AdvancedAgentConfiguration) GetBackendDevice() *string {
	if o == nil {
		return nil
	}
	return o.BackendDevice
}
