// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type Agent struct {
	ID                    int64                       `json:"id"`
	Name                  string                      `json:"name"`
	ClientSignature       string                      `json:"client_signature"`
	CommandParameters     *string                     `json:"command_parameters"`
	CPUOnly               bool                        `json:"cpu_only"`
	Trusted               bool                        `json:"trusted"`
	IgnoreErrors          bool                        `json:"ignore_errors"`
	OperatingSystem       string                      `json:"operating_system"`
	Devices               []string                    `json:"devices"`
	AdvancedConfiguration *AdvancedAgentConfiguration `json:"advanced_configuration,omitempty"`
}

func (o *Agent) GetID() int64 {
	if o == nil {
		return 0
	}
	return o.ID
}

func (o *Agent) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *Agent) GetClientSignature() string {
	if o == nil {
		return ""
	}
	return o.ClientSignature
}

func (o *Agent) GetCommandParameters() *string {
	if o == nil {
		return nil
	}
	return o.CommandParameters
}

func (o *Agent) GetCPUOnly() bool {
	if o == nil {
		return false
	}
	return o.CPUOnly
}

func (o *Agent) GetTrusted() bool {
	if o == nil {
		return false
	}
	return o.Trusted
}

func (o *Agent) GetIgnoreErrors() bool {
	if o == nil {
		return false
	}
	return o.IgnoreErrors
}

func (o *Agent) GetOperatingSystem() string {
	if o == nil {
		return ""
	}
	return o.OperatingSystem
}

func (o *Agent) GetDevices() []string {
	if o == nil {
		return []string{}
	}
	return o.Devices
}

func (o *Agent) GetAdvancedConfiguration() *AdvancedAgentConfiguration {
	if o == nil {
		return nil
	}
	return o.AdvancedConfiguration
}
