// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type AgentConfiguration struct {
	Config     AdvancedAgentConfiguration `json:"config"`
	APIVersion int64                      `json:"api_version"`
}

func (o *AgentConfiguration) GetConfig() AdvancedAgentConfiguration {
	if o == nil {
		return AdvancedAgentConfiguration{}
	}
	return o.Config
}

func (o *AgentConfiguration) GetAPIVersion() int64 {
	if o == nil {
		return 0
	}
	return o.APIVersion
}
