// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type AttackResourceFile struct {
	// The id of the resource file
	ID int64 `json:"id"`
	// The download URL of the resource file
	DownloadURL string `json:"download_url"`
	// The MD5 checksum of the resource file
	Checksum string `json:"checksum"`
	// The name of the resource file
	FileName string `json:"file_name"`
}

func (o *AttackResourceFile) GetID() int64 {
	if o == nil {
		return 0
	}
	return o.ID
}

func (o *AttackResourceFile) GetDownloadURL() string {
	if o == nil {
		return ""
	}
	return o.DownloadURL
}

func (o *AttackResourceFile) GetChecksum() string {
	if o == nil {
		return ""
	}
	return o.Checksum
}

func (o *AttackResourceFile) GetFileName() string {
	if o == nil {
		return ""
	}
	return o.FileName
}
