// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AuthenticationResult struct {
	Authenticated bool  `json:"authenticated"`
	AgentID       int64 `json:"agent_id"`
}

func (o *AuthenticationResult) GetAuthenticated() bool {
	if o == nil {
		return false
	}
	return o.Authenticated
}

func (o *AuthenticationResult) GetAgentID() int64 {
	if o == nil {
		return 0
	}
	return o.AgentID
}
