// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type CrackerUpdate struct {
	// A new version of the cracker binary is available
	Available bool `json:"available"`
	// The latest version of the cracker binary
	LatestVersion *string `json:"latest_version,omitempty"`
	// The download URL of the new version
	DownloadURL *string `json:"download_url,omitempty"`
	// The name of the executable
	ExecName *string `json:"exec_name,omitempty"`
	// A message about the update
	Message *string `json:"message,omitempty"`
}

func (o *CrackerUpdate) GetAvailable() bool {
	if o == nil {
		return false
	}
	return o.Available
}

func (o *CrackerUpdate) GetLatestVersion() *string {
	if o == nil {
		return nil
	}
	return o.LatestVersion
}

func (o *CrackerUpdate) GetDownloadURL() *string {
	if o == nil {
		return nil
	}
	return o.DownloadURL
}

func (o *CrackerUpdate) GetExecName() *string {
	if o == nil {
		return nil
	}
	return o.ExecName
}

func (o *CrackerUpdate) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}
