// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type CrackerUpdate struct {
	Available     bool    `json:"available"`
	LatestVersion *string `json:"latest_version,omitempty"`
	DownloadURL   *string `json:"download_url,omitempty"`
	ExecName      *string `json:"exec_name,omitempty"`
	Message       *string `json:"message,omitempty"`
}

func (o *CrackerUpdate) GetAvailable() bool {
	if o == nil {
		return false
	}
	return o.Available
}

func (o *CrackerUpdate) GetLatestVersion() *string {
	if o == nil {
		return nil
	}
	return o.LatestVersion
}

func (o *CrackerUpdate) GetDownloadURL() *string {
	if o == nil {
		return nil
	}
	return o.DownloadURL
}

func (o *CrackerUpdate) GetExecName() *string {
	if o == nil {
		return nil
	}
	return o.ExecName
}

func (o *CrackerUpdate) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}
