// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type HashcatGuess struct {
	// The base value used for the guess (for example, the mask)
	GuessBase string `json:"guess_base"`
	// The number of times the base value was used
	GuessBaseCount int64 `json:"guess_base_count"`
	// The offset of the base value
	GuessBaseOffset int64 `json:"guess_base_offset"`
	// The percentage completion of the base value
	GuessBasePercentage float64 `json:"guess_base_percentage"`
	// The modifier used for the guess (for example, the wordlist)
	GuessMod string `json:"guess_mod"`
	// The number of times the modifier was used
	GuessModCount int64 `json:"guess_mod_count"`
	// The offset of the modifier
	GuessModOffset int64 `json:"guess_mod_offset"`
	// The percentage completion of the modifier
	GuessModPercentage float64 `json:"guess_mod_percentage"`
	// The mode used for the guess
	GuessMode int64 `json:"guess_mode"`
}

func (o *HashcatGuess) GetGuessBase() string {
	if o == nil {
		return ""
	}
	return o.GuessBase
}

func (o *HashcatGuess) GetGuessBaseCount() int64 {
	if o == nil {
		return 0
	}
	return o.GuessBaseCount
}

func (o *HashcatGuess) GetGuessBaseOffset() int64 {
	if o == nil {
		return 0
	}
	return o.GuessBaseOffset
}

func (o *HashcatGuess) GetGuessBasePercentage() float64 {
	if o == nil {
		return 0.0
	}
	return o.GuessBasePercentage
}

func (o *HashcatGuess) GetGuessMod() string {
	if o == nil {
		return ""
	}
	return o.GuessMod
}

func (o *HashcatGuess) GetGuessModCount() int64 {
	if o == nil {
		return 0
	}
	return o.GuessModCount
}

func (o *HashcatGuess) GetGuessModOffset() int64 {
	if o == nil {
		return 0
	}
	return o.GuessModOffset
}

func (o *HashcatGuess) GetGuessModPercentage() float64 {
	if o == nil {
		return 0.0
	}
	return o.GuessModPercentage
}

func (o *HashcatGuess) GetGuessMode() int64 {
	if o == nil {
		return 0
	}
	return o.GuessMode
}
