// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type HashcatGuess struct {
	GuessBase           string  `json:"guess_base"`
	GuessBaseCount      int64   `json:"guess_base_count"`
	GuessBaseOffset     int64   `json:"guess_base_offset"`
	GuessBasePercentage float64 `json:"guess_base_percentage"`
	GuessMod            string  `json:"guess_mod"`
	GuessModCount       int64   `json:"guess_mod_count"`
	GuessModOffset      int64   `json:"guess_mod_offset"`
	GuessModPercentage  float64 `json:"guess_mod_percentage"`
	GuessMode           int64   `json:"guess_mode"`
}

func (o *HashcatGuess) GetGuessBase() string {
	if o == nil {
		return ""
	}
	return o.GuessBase
}

func (o *HashcatGuess) GetGuessBaseCount() int64 {
	if o == nil {
		return 0
	}
	return o.GuessBaseCount
}

func (o *HashcatGuess) GetGuessBaseOffset() int64 {
	if o == nil {
		return 0
	}
	return o.GuessBaseOffset
}

func (o *HashcatGuess) GetGuessBasePercentage() float64 {
	if o == nil {
		return 0.0
	}
	return o.GuessBasePercentage
}

func (o *HashcatGuess) GetGuessMod() string {
	if o == nil {
		return ""
	}
	return o.GuessMod
}

func (o *HashcatGuess) GetGuessModCount() int64 {
	if o == nil {
		return 0
	}
	return o.GuessModCount
}

func (o *HashcatGuess) GetGuessModOffset() int64 {
	if o == nil {
		return 0
	}
	return o.GuessModOffset
}

func (o *HashcatGuess) GetGuessModPercentage() float64 {
	if o == nil {
		return 0.0
	}
	return o.GuessModPercentage
}

func (o *HashcatGuess) GetGuessMode() int64 {
	if o == nil {
		return 0
	}
	return o.GuessMode
}
