// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/unclesp1d3r/cipherswarm-agent-sdk-go/internal/utils"
	"time"
)

type Task struct {
	// The id of the task
	ID int64 `json:"id"`
	// The id of the attack
	AttackID int64 `json:"attack_id"`
	// The time the task was started
	StartDate time.Time `json:"start_date"`
	// The status of the task
	Status string `json:"status"`
	// The offset of the keyspace
	Skip *int64 `json:"skip,omitempty"`
	// The limit of the keyspace
	Limit *int64 `json:"limit,omitempty"`
}

func (t Task) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *Task) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *Task) GetID() int64 {
	if o == nil {
		return 0
	}
	return o.ID
}

func (o *Task) GetAttackID() int64 {
	if o == nil {
		return 0
	}
	return o.AttackID
}

func (o *Task) GetStartDate() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.StartDate
}

func (o *Task) GetStatus() string {
	if o == nil {
		return ""
	}
	return o.Status
}

func (o *Task) GetSkip() *int64 {
	if o == nil {
		return nil
	}
	return o.Skip
}

func (o *Task) GetLimit() *int64 {
	if o == nil {
		return nil
	}
	return o.Limit
}
